export const UPDATE_EVENT = 'UPDATE_EVENT';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERRORS = 'GET_CATEGORIES_ERRORS';

export const GET_COORDINATORS = 'GET_COORDINATORS';
export const GET_COORDINATORS_SUCCESS = 'GET_COORDINATORS_SUCCESS';
export const GET_COORDINATORS_ERRORS = 'GET_COORDINATORS_ERRORS';


export const SUBMIT_EVENT = 'SUBMIT_EVENT';